import "oaidl.idl";
import "ocidl.idl";

[object, uuid(E8DB58B7-1D7E-486E-9C1B-5F216A85023D), dual, nonextensible, pointer_default(unique)]
interface IProcessRunnerResult : IDispatch
{
  [propget, id(1)] HRESULT StdOut([out, retval] BSTR* val);
  [propget, id(2)] HRESULT StdErr([out, retval] BSTR* val);
  [propget, id(3)] HRESULT ExitCode([out, retval] long* val);
};

[object, uuid(7c4f5751-db2c-401d-94d4-fc286b714047), dual, nonextensible, pointer_default(unique)]
interface IProcessRunner : IDispatch
{
  [id(1)] HRESULT Run([in] BSTR executablePath, [in, defaultvalue(0)] IDispatch* commandLineArgumentsJsArray, [in, defaultvalue("")] BSTR workingDirectory, [out, retval] IProcessRunnerResult** res);
};

[object, uuid(CE86F2EC-8EC9-48C4-A3C6-0FB265011E86), dual, nonextensible, pointer_default(unique)]
interface IFileMimeTypeDetectorResult : IDispatch
{
  [propget, id(1)] HRESULT MimeType([out, retval] BSTR* val);
  [propget, id(2)] HRESULT Encoding([out, retval] BSTR* val);
};

[object, uuid(C5C6B6D4-48BB-4467-BD45-A760780DDA72), dual, nonextensible, pointer_default(unique)]
interface IFileMimeTypeDetector : IDispatch
{
  [id(1)] HRESULT DetectMimeType([in] BSTR fileFullName, [out, retval] IFileMimeTypeDetectorResult** res);
};

[object, uuid(19337548-7C0D-4437-866E-4E47A4CE662B), dual, nonextensible, pointer_default(unique)]
interface IStringFormatter : IDispatch
{
  [id(1)] HRESULT Format([in] BSTR formatString, [in, defaultvalue(0)] BSTR arg1, [in, defaultvalue(0)] BSTR arg2, [in, defaultvalue(0)] BSTR arg3,
    [in, defaultvalue(0)] BSTR arg4, [in, defaultvalue(0)] BSTR arg5, [in, defaultvalue(0)] BSTR arg6, [in, defaultvalue(0)] BSTR arg7,
    [in, defaultvalue(0)] BSTR arg8, [in, defaultvalue(0)] BSTR arg9, [in, defaultvalue(0)] BSTR arg10, [in, defaultvalue(0)] BSTR arg11,
    [in, defaultvalue(0)] BSTR arg12, [out, retval] BSTR* res);
};

[object, uuid(D29821A8-51F9-40F3-B065-6BF073238124), dual, nonextensible, pointer_default(unique)]
interface IMediaInfoRetriever : IDispatch
{
  [id(1)] HRESULT Open([in] BSTR mediaFileFullName);
  [id(2)] HRESULT Get([in] UINT streamKind, [in] UINT streamNumber, [in] BSTR parameter, [in, defaultvalue(1)] UINT infoKind, [in, defaultvalue(0)] UINT searchKind, [out, retval] BSTR* res);
  [id(3)] HRESULT GetI([in] UINT streamKind, [in] UINT streamNumber, [in] UINT parameter, [in, defaultvalue(1)] UINT infoKind, [out, retval] BSTR* res);
  [id(4)] HRESULT Count_Get([in] UINT streamKind, [in, defaultvalue(/* UINT_MAX */ 0xFFFFFFFF)] UINT streamNumber, [out, retval] UINT64* res);
  [id(5)] HRESULT Option([in] BSTR option, [in, defaultvalue("")] BSTR value, [out, retval] BSTR* res);
  [id(6)] HRESULT Inform([out, retval] BSTR* res);
  [id(7)] HRESULT Option_Static([in] BSTR option, [in, defaultvalue("")] BSTR value, [out, retval] BSTR* res);
  [id(8)] HRESULT Close();
};

[uuid(010ccc04-f6ea-46e5-854d-67d1fb42c7f3), version(1.0)]
library DOpusScriptingExtensionsLib
{
	importlib("stdole2.tlb");

	[uuid(12de862c-a197-4f45-a282-cc9022eb51f1)]
	coclass ProcessRunner
	{
		[default] interface IProcessRunner;
	};

  [uuid(40D713DE-D9F4-465F-BF4C-0E66FED4F2C8)]
  coclass ProcessRunnerResult
  {
    [default] interface IProcessRunnerResult;
  };

  [uuid(69F3ABCC-E14F-43FF-B739-24BE0538E292)]
  coclass FileMimeTypeDetectorResult
  {
    [default] interface IFileMimeTypeDetectorResult;
  };
  
  [uuid(0AD4E772-58F4-4AD5-84B4-8639609C81A5)]
  coclass FileMimeTypeDetector
  {
    [default] interface IFileMimeTypeDetector;
  };

  [uuid(933053BD-E75C-473F-A201-9C9586C1AA1A)]
  coclass StringFormatter
  {
    [default] interface IStringFormatter;
  };

  [uuid(4349DCF9-4E85-47CB-917F-A6EEBBD11B3F)]
  coclass MediaInfoRetriever
  {
    [default] interface IMediaInfoRetriever;
  };
};

import "shobjidl.idl";
